version: "2.0"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
  web:
    image: miles1618/dockerfibonacci
    command: python app.py
    environment:
      - FLASK_PORT=5000
      - FLASK_DEBUG=True
    depends_on:
      - redis
    ports:
      - 5000:5000
    volumes:
      - ./flaskapp:/opt/flaskapp
